####### GET Orders #######
GET http://localhost:4004/odata/v4/manage-orders/Orders

###GET Client by Email
GET http://localhost:4004/odata/v4/manage-orders/Orders('client1@client1.com')


####### CREATE Order #######
POST http://localhost:4004/odata/v4/manage-orders/Orders HTTP/1.1
Content-Type: application/json

{
    "ClientEmail": "mauricio@mail.de",
    "FirstName": "Mauricio",
    "LastName": "Vieira dos Santos",
    "CreatedOn": "2000-01-01"
}

####### UPDATE Order #######
PUT http://localhost:4004/odata/v4/manage-orders/Orders('client1@client1.com') HTTP/1.1
Content-Type: application/json

{
    "FirstName": "Fred",
    "LastName": "Mercury"
}

####### DELETE Order #######
DELETE http://localhost:4004/odata/v4/manage-orders/Orders('client1@client1.com')

####### GET Customer Rate - Function #######
GET http://localhost:4004/odata/v4/manage-orders/getClientTaxRate(clientEmail='client1@client1.com')

####### POST Cancell Order - Action #######
POST http://localhost:4004/odata/v4/manage-orders/cancelOrder
Content-Type: application/json

{"clientEmail" : "client2@client2.com"}

####### GET Customer Rate - Function Bound #######
GET http://localhost:4004/odata/v4/manage-orders/Orders('client1@client1.com')/ManageOrders.getClientTaxRate(clientEmail='client1@client1.com')

####### POST Cancell Order - Action Bound #######
POST http://localhost:4004/odata/v4/manage-orders/Orders('client1@client1.com')/ManageOrders.cancelOrder
Content-Type: application/json

{"clientEmail" : "client2@client2.com"}

####### GET Incidents #######
GET http://localhost:4004/odata/v4/sapbackend-exit/Incidents